### ISSUE TITLE
Is issue management support planned or is gitissue explicitly read-only?

### ISSUE THREAD

**Issue by masochist** [julenpardo/Gitssue#38]
I'm looking for a tool to manage my issues from the commandline and would like to use gitissue for both read and write operations. If it's an explicit goal for gitissue to not support write operations, I'd like to know before I look into adding support for it.

**Comment by julenpardo** [comment]
Hello @masochist,

Thank you so much for your question.

Support for write operations (open issues, add comments, close them, etc.) were on my mind, but I haven't planned when to add that support. Honestly I thought that gitssue was used just by me, so actually I've never considered something like a roadmap.

But as I see that gitssue may be actually used by others, I'll begin with this asap. :)

**Comment by julenpardo** [comment]
Hey @masochist, 

I've released a [v2.0.0 version](https://github.com/julenpardo/Gitssue/releases/tag/v2.0.0), with support for the following write operations: create and close issues, and adding comments to these.

You can either download manually, or upgrade it with pip:

```
sudo pip3 install --upgrade gitssue
```

Regards, and many thanks for your interest! And any suggestion and feedback is appreciated.
